use_frameworks!

platform :ios, '13.0'

target 'LithoOnboarding_Example' do
  pod 'LithoOnboarding', :path => '../'
  pod 'LithoOperators', git: 'https://github.com/ThryvInc/LithoOperators'
  pod 'fuikit/Core', git: 'https://github.com/ThryvInc/fuikit'
  pod 'LithoUtils', git: 'https://github.com/ThryvInc/litho-utils'
  target 'LithoOnboarding_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
