use_frameworks!

platform :ios, '9.0'

target 'LithoOnboarding_Example' do
  pod 'LithoOnboarding', :path => '../'

  target 'LithoOnboarding_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
